name: CI

on:
  push:
    paths:
      - ".github/workflows/*.yaml"
      - ".github/workflows/*.yml"
      - "Cargo.toml"
      - "crates/**"
      - "src/**"
      - "tests/**"
      - "xtask/**"
  pull_request:
    paths:
      - "Cargo.toml"
      - "crates/**"
      - "src/**"
      - "tests/**"
      - "xtask/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: Run CI tasks
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install clippy and rustfmt
        run: |
          rustup update
          rustup component add clippy rustfmt

      - name: Install CI deps
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y clang llvm

      - run: cargo xtask ci
