name: CI

on:
  push:
    paths-ignore:
      - "docs/**"
      - "examples/**"
      - "CHANGELOG.md"
      - "LICENSE"
      - "README.md"
    branches-ignore:
      - "dev-noci/**"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "examples/**"
      - "CHANGELOG.md"
      - "LICENSE"
      - "README.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  ci-linux:
    runs-on: ubuntu-latest
    env:
      BOFLINK_TEST_CLANG: clang-20
      BOFLINK_TEST_DLLTOOL: llvm-dlltool-20

    steps:
      - uses: actions/checkout@v4

      - name: Install clippy and rustfmt
        run: |
          rustup update
          rustup component add clippy rustfmt

      - name: Install CI deps
        run: |
          sudo apt-get install -y clang-20 llvm-20

      - run: cargo xtask ci

  ci-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install clippy and rustfmt
        run: |
          rustup update
          rustup component add clippy rustfmt

      - run: cargo xtask ci
